### ISSUE TITLE
Broke queue:work

### ISSUE THREAD

**Issue by StefanoDucci** [convenia/Pigeon#98]
**Describe the bug**
When I try to send two messagens for the same queue:work command, the job fails.

**To Reproduce**
1. Create a queue:work
2. Publish a message by job
3. See error

**Comment by jleonardolemos** [comment]
This is really happening. I will reopen the issue in order to think/propose a fix

**Comment by kauanslr** [comment]
Can you provide some logs of what's happening? i've tried to reproduce but without success

**Comment by jleonardolemos** [comment]
@kauanslr if you run queue work the first job dispatched will work fine, if the queue takes more than 20 seconds to get another job AMQP related rabbit will close the connection and the jobs will fail for ever.

The `isConnected` connection method into RabbitDriver `getConnection` always returns true :/

Stack trace: 
```
Next PhpAmqpLib\\Exception\\AMQPConnectionClosedException: Connection reset by peer in /home/vagrant/code/laravel/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:257
Stack trace:
#1 /home/vagrant/code/laravel/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(502): PhpAmqpLib\\Connection\\AbstractConnection->write()
#0 /home/vagrant/code/laravel/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(376): PhpAmqpLib\\Wire\\IO\\StreamIO->write()
#2 /home/vagrant/code/laravel/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(247): PhpAmqpLib\\Connection\\AbstractConnection->send_channel_method_frame()
#3 /home/vagrant/code/laravel/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(387): PhpAmqpLib\\Channel\\AbstractChannel->send_method_frame()
#4 /home/vagrant/code/packages/Pigeon/src/Drivers/Driver.php(48): PhpAmqpLib\\Channel\\AMQPChannel->exchange_declare()
#5 /home/vagrant/code/packages/Pigeon/src/PigeonManager.php(52): Convenia\\Pigeon\\Drivers\\Driver->exchange()
#6 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Convenia\\Pigeon\\PigeonManager->__call()
#7 /home/vagrant/code/laravel/app/Jobs/Test.php(34): Illuminate\\Support\\Facades\\Facade::__callStatic()
#8 [internal function]: App\\Jobs\\Test->handle()
#9 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#10 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#14 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#15 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#16 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#18 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#19 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#20 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#22 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#23 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call()
#24 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\\Queue\\Jobs\\Job->fire()
#25 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process()
#26 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob()
#27 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#28 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#29 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#30 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#31 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#33 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#34 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#35 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#36 /home/vagrant/code/laravel/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#37 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#38 /home/vagrant/code/laravel/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run()
#39 /home/vagrant/code/laravel/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#40 /home/vagrant/code/laravel/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#41 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#42 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#43 /home/vagrant/code/laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#44 {main}, 2020-03-14 20:07:55)) at /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
[stacktrace]
#0 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#1 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\\Database\\Connection->run()
#2 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\\Database\\Connection->statement()
#3 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#4 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#5 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php(62): Illuminate\\Database\\Query\\Builder->insertGetId()
#6 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(200): Illuminate\\Queue\\Failed\\DatabaseFailedJobProvider->log()
#7 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(149): Illuminate\\Queue\\Console\\WorkCommand->logFailedJob()
#8 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(369): Illuminate\\Queue\\Console\\WorkCommand->Illuminate\\Queue\\Console\\{closure}()
#9 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#10 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(185): Illuminate\\Events\\Dispatcher->dispatch()
#11 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(482): Illuminate\\Queue\\Jobs\\Job->fail()
#12 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(469): Illuminate\\Queue\\Worker->failJob()
#13 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(399): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts()
#14 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(372): Illuminate\\Queue\\Worker->handleJobException()
#15 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process()
#16 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob()
#17 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#18 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#19 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#20 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#21 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#23 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#24 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#25 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#26 /home/vagrant/code/laravel/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#27 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#28 /home/vagrant/code/laravel/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run()
#29 /home/vagrant/code/laravel/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#30 /home/vagrant/code/laravel/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#31 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#32 /home/vagrant/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#33 /home/vagrant/code/laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
```

**Comment by jleonardolemos** [comment]
I was thinking about include a config 'perssist_connection' so we can set this to false on queued jobs but it seens to be dangerous considering connections amount, the rabbit instance memory can blow up. @kauanslr

**Comment by jleonardolemos** [comment]
Actually there is a dummy solution on app side too, just close the connection manually:

```
Pigeon::exchange('cu')->publish([
    'sujo'
]);

Pigeon::getConnection()->close();
```

This will force reconnect method on RabbitDriver
